name: Build
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v4
        with:
          path: ./data
          key: exd-data

      - name: Download EXD files
        uses: WorkingRobot/ffxiv-downloader@07c916aed33cabde26d61765ac75cf93fda6f6fb
        id: downloader      
        with:
          output-path: ./data
          file-regex: '^sqpack\/ffxiv\/0a0000\..+$'

      - name: Restore
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build GeneratedSheets3 --configuration Release --no-restore --property:GamePath=/github/workspace/data/sqpack

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GeneratedSheets
          path: bin/Release/net8.0
          if-no-files-found: error

      
