name: Build

on:
  push

permissions:
  contents: write
  packages: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/exd-data
          key: exd-data

      - name: Download EXD files
        uses: WorkingRobot/ffxiv-downloader@e3f4a8e8872dbb8cf2a8b00950106b5a88d9a6df
        id: downloader      
        with:
          output-path: /github/workspace/exd-data
          file-regex: '^sqpack\/ffxiv\/0a0000\..+$'

      - name: Restore
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build ExdSheets -c Release --no-restore --property:GamePath=${{ github.workspace }}/exd-data/sqpack /p:ContinuousIntegrationBuild=true

      - name: Pack
        run: |
          dotnet pack ExdSheets -c Release --no-build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExdSheets
          path: ExdSheets/bin/Release
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        id: release
        with:
          files: |
            ExdSheets/bin/Release/*.nupkg
            ExdSheets/bin/Release/*.snupkg

      - name: Upload to GPR
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push ExdSheets/bin/Release/*.nupkg -s https://nuget.pkg.github.com/${{github.repository_owner}} -k ${{secrets.GITHUB_TOKEN}}

      - name: Upload to NuGet
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push ExdSheets/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}


