name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/exd-data
          key: exd-data

      - name: Download EXD files
        uses: WorkingRobot/ffxiv-downloader@631311890c71f584c84380d67fb729717a830c9e
        id: downloader      
        with:
          output-path: /github/workspace/exd-data
          file-regex: '^sqpack\/ffxiv\/0a0000\..+$'

      - name: Restore
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build ExdSheets --configuration Release --no-restore --property:GamePath=${{ github.workspace }}/exd-data/sqpack

      - name: Pack
        run: |
          dotnet pack ExdSheets --configuration Release --no-build --output .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExdSheets
          path: ExdSheets/bin/Release
          if-no-files-found: error

      - name: Upload Nupkg
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push ExdSheets/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}


